### ISSUE TITLE
虽然不知道这个项目还有没有人维护，但是associated-data里面是挂了的

### ISSUE THREAD

**Issue by jiahao1889** [leancloud/lean-cache-demos#2]
fetchUserFromCache里面少了个return
以及映射id的函数只有存的时候用了，拿的时候没有写
完全用不了

**Comment by jysperm** [comment]
该项目已被归档，后续将不再维护，请在 [leancloud/leanengine-nodejs-demos](https://github.com/leancloud/leanengine-nodejs-demos) 中查看有关 LeanCache 的最新示例。
